"""
test_husks_init.py -- Test husks init generated project.

Beta Gate A5: Make husks init produce a valid seed project.

Tests that the project generated by `husks init` passes `husks check`
and `husks run --stub`.
"""

import json
import tempfile
import shutil
from pathlib import Path

from conftest import run_husks_cli
from husks.design.locke import from_json, check, run
from husks.setup import _DEMO_DESIGN

import pytest


@pytest.mark.skip(reason="Blocker #10: Demo design quarantined, core-bootstrap is default")
@pytest.mark.gate_a


def test_demo_design_is_valid():
    """The demo design template passes validation."""
    errors = check(_DEMO_DESIGN)
    assert len(errors) == 0, f"Demo design should be valid, got errors: {errors}"


@pytest.mark.skip(reason="Blocker #10: Demo design quarantined, core-bootstrap is default")
@pytest.mark.gate_a


def test_demo_design_has_required_fields():
    """The demo design has all required fields."""
    assert "name" in _DEMO_DESIGN
    assert "fuel" in _DEMO_DESIGN
    assert "target" in _DEMO_DESIGN
    assert "rules" in _DEMO_DESIGN
    assert len(_DEMO_DESIGN["rules"]) > 0


@pytest.mark.skip(reason="Blocker #10: Demo design quarantined, core-bootstrap is default")
@pytest.mark.gate_a


def test_demo_design_runs_with_stub():
    """The demo design runs successfully with stub oracle."""
    tmpdir = tempfile.mkdtemp(prefix="demo-stub-")
    try:
        site = Path(tmpdir) / "site"
        site.mkdir()

        def stub_oracle(S, rule_name, recipe, outputs):
            """Stub oracle that writes placeholder outputs."""
            from husks.build import write_path
            for o in outputs:
                output_path = write_path(S, o)
                Path(output_path).parent.mkdir(parents=True, exist_ok=True)
                Path(output_path).write_text(f"# Stub output from {rule_name}\n")
            return {"tokens_in": 10, "tokens_out": 10, "cost_usd": 0.001, "fuel_steps": 1}

        S = run(_DEMO_DESIGN, site=str(site), oracle_backend=stub_oracle)
        assert S["status"] == "committed", f"Demo should commit with stub, got {S['status']}"

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


@pytest.mark.skip(reason="Blocker #10: Demo design quarantined, core-bootstrap is default")
@pytest.mark.gate_a


def test_husks_init_creates_valid_project():
    """husks init creates a project that passes check and run --stub."""
    tmpdir = tempfile.mkdtemp(prefix="init-test-")
    try:
        # Run husks init in temp directory
        result = run_husks_cli("init", str(tmpdir))

        # Should succeed
        assert result.returncode == 0, (
            f"husks init should succeed, got {result.returncode}\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )

        # Should create design.json
        design_path = Path(tmpdir) / "design.json"
        assert design_path.exists(), "design.json should be created"

        # design.json should be valid JSON
        with open(design_path) as f:
            design = json.load(f)

        # Should pass validation
        errors = check(design)
        assert len(errors) == 0, f"Generated design should be valid, got: {errors}"

        # Should have expected structure
        assert design["name"] == "demo"
        assert design["fuel"] > 0
        assert "target" in design
        assert len(design["rules"]) > 0

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


@pytest.mark.beta


@pytest.mark.gate_a


def test_husks_init_check_command():
    """Generated project passes `husks check`."""
    tmpdir = tempfile.mkdtemp(prefix="init-check-")
    try:
        # Run husks init
        run_husks_cli("init", str(tmpdir))

        # Run husks check (init creates core-bootstrap.locke, not design.json)
        design_path = Path(tmpdir) / "core-bootstrap.locke"
        result = run_husks_cli("check", str(design_path), cwd=str(tmpdir))

        assert result.returncode == 0, (
            f"husks check should pass on generated project\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
        # check is silent on success (exit code 0 is the indicator)

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


@pytest.mark.beta


@pytest.mark.gate_a


def test_husks_init_run_stub_command():
    """Generated project succeeds with `husks run --stub`."""
    tmpdir = tempfile.mkdtemp(prefix="init-run-")
    try:
        # Run husks init
        run_husks_cli("init", str(tmpdir))

        # Create site directory
        site = Path(tmpdir) / "site"
        site.mkdir()

        # Run husks run --stub (init creates core-bootstrap.locke)
        design_path = Path(tmpdir) / "core-bootstrap.locke"
        result = run_husks_cli(
            "run", str(design_path), "--stub", "--site", str(site), cwd=str(tmpdir)
        )

        # Should succeed (exit 0 = committed)
        assert result.returncode == 0, (
            f"husks run --stub should succeed on generated project\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )

        # Should show sealed status in DAG view
        assert "sealed" in result.stdout.lower()

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


@pytest.mark.beta


@pytest.mark.gate_a


def test_husks_init_creates_claude_md():
    """husks init creates CLAUDE.md with project conventions."""
    tmpdir = tempfile.mkdtemp(prefix="init-claude-")
    try:
        run_husks_cli("init", str(tmpdir))

        claude_md = Path(tmpdir) / "CLAUDE.md"
        assert claude_md.exists(), "CLAUDE.md should be created"

        content = claude_md.read_text()
        assert "Husks" in content
        assert "design.locke" in content
        assert "workflow" in content.lower() or "Workflow" in content

    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)
